### PR TITLE
fix: update cloud command

### LINKED ISSUE #27: Replace `k6 cloud` command with `k6 cloud run` command
V0.53 of k6 introduced the `k6 cloud run` command which replaces the existing `k6 cloud` command. Currently, it only shows a warning in the console but in future, the old command will be deprecated. 
Hence, we should update the GitHub action to use the new command for new versions and old command for older version.

### PR DESCRIPTION
**Pull request by greyvugrin**
### Changes

- Command updates for k6 versions >= 0.54.0 [0.54 change details](https://github.com/grafana/k6/blob/20369d707f5ee6d7fd8a995972ccdd6b86db2b5d/release%20notes/v0.54.0.md?plain=1#L122)
  - Updates the cloud command from `cloud` to `cloud run`. (Closes #27)
  - Updates the flag for local cloud execution from `--out=cloud` to `--local-execution`.
- Add `semver` for version comparison, and added a mechanism to have different tests for different k6 versions

### Notes

> By default, using the `--local-execution` flag uploads the test archive to Grafana Cloud k6. If you want to disable this upload, use the `--no-archive-upload` flag.
> 
> The `--local-execution` flag currently functions similarly to the `k6 run -o cloud` command, which is now considered deprecated (though it is not planned to be removed). Future updates will enhance `--local-execution` with additional capabilities that the `k6 run -o cloud` command does not offer.

If you want me to adjust the command to skip the archive upload, let me know. Figured preserving the flag behavior default was preferable in this case.

~~I believe that the `--out=cloud` flag may also have been responsible for these messages from a recent run:~~
Screen Shot 2025-04-07 at 1 57 14 PM

### CODE REVIEW

**Comment by greyvugrin** [comment]
@DefCon-007 did you have any feedback on the changes so far? Also, should I make a separate PR for the `cloud-comment-on-pr` adjustment I mentioned above or tackle that here?

**Comment by DefCon-007** [comment]
Hey @greyvugrin, sorry I missed this. Thanks a lot for the changes, amazing work. The run k6 action can actually be used with older k6 versions as well in which case this command will fail. You can use [this](https://github.com/grafana/run-k6-action/blob/main/src/k6helper.ts#L281) helper function to determine the currently installed k6 version and use appropriate command. 
Adding a new CI test to validate the action works for both old and new k6 version will also be very helpful.

**Comment by greyvugrin** [comment]
@DefCon-007 excellent - added those updates in my latest push.

File: src/k6helper.ts [hunk 1]
```diff
@@ -290,3 +297,37 @@ export function getInstalledK6Version(): string {
...
 }
+
+/**
+ * Compares two semantic version strings and checks if version1 is at least (greater than or equal to) version2.
+ *
+ * @param {string} version1 - The first version string (e.g., "0.56.0")
+ * @param {string} version2 - The second version string (e.g., "0.55.0")
+ * @returns {boolean} True if version1 is at least version2, false otherwise
+ */
+export function isVersionAtLeast(
```
Comment (DefCon-007) [inline src/k6helper.ts:308]: Why not use something like  - https://www.npmjs.com/package/semver

Comment (greyvugrin) [reply src/k6helper.ts:308]: Wasn't sure you would want me to add a dependency for a small function like this, but happy to use `semver` if that's preferred. Gives some flexibility for the future too (they include more utility functions to compare versions). Will update and push

**Review by DefCon-007 — APPROVED** [review]
